# 输出题

### 类型输出



### 异步和事件循环

#### 基本顺序

```js
const promise = new Promise((resolve, reject) => {
  console.log(1);
  console.log(2);
});
promise.then(() => {
  console.log(3);
});
console.log(4);
```

```
1 
2 
4
```

promise.then 是微任务，它会在所有的宏任务执行完之后才会执行，同时需要promise内部的状态发生变化，因为这里内部没有发生变化，一直处于pending状态，所以不输出3。

#### promise状态

```js
const promise1 = new Promise((resolve, reject) => {
  console.log('promise1')
  resolve('resolve1')
})
const promise2 = promise1.then(res => {
  console.log(res)
})
console.log('1', promise1);
console.log('2', promise2);
```

```
promise1
1 Promise{<resolved>: resolve1}
2 Promise{<pending>}
resolve1
```

直接打印promise1，会打印出它的状态值和参数

代码执行过程如下：

1.  script是一个宏任务，按照顺序执行这些代码；
2.  首先进入Promise，执行该构造函数中的代码，打印`promise1`；
3.  碰到`resolve`函数, 将`promise1`的状态改变为`resolved`, 并将结果保存下来；
4.  碰到`promise1.then`这个微任务，将它放入微任务队列；
5.  `promise2`是一个新的状态为`pending`的`Promise`；
6.  执行同步代码1， 同时打印出`promise1`的状态是`resolved`；
7.  执行同步代码2，同时打印出`promise2`的状态是`pending`；
8.  宏任务执行完毕，查找微任务队列，发现`promise1.then`这个微任务且状态为`resolved`，执行它。

#### promise套setTimeout

```js
const promise = new Promise((resolve, reject) => {
  console.log(1);
  setTimeout(() => {
    console.log("timerStart");
    resolve("success");
    console.log("timerEnd");
  }, 0);
  console.log(2);
});
promise.then((res) => {
  console.log(res);
});
console.log(4);
```

```js
1
2
4
timerStart
timerEnd
success
```

代码执行过程如下：

-   首先遇到`Promise`构造函数，会先执行里面的内容，打印`1`；
-   遇到定时器`steTimeout`，它是一个宏任务，放入宏任务队列；
-   继续向下执行，打印出2；
-   由于`Promise`的状态此时还是`pending`，所以`promise.then`先不执行；
-   继续执行下面的同步任务，打印出4；
-   此时微任务队列没有任务，继续执行下一轮宏任务，执行`steTimeout`；
-   首先执行`timerStart`，然后遇到了`resolve`，将`promise`的状态改为`resolved`且保存结果并将之前的`promise.then`推入微任务队列，再执行`timerEnd`；
-   执行完这个宏任务，就去执行微任务`promise.then`，打印出`resolve`的结果。

#### setTimeout套promise

```js
Promise.resolve().then(() => {
  console.log('promise1');
  const timer2 = setTimeout(() => {
    console.log('timer2')
  }, 0)
});
const timer1 = setTimeout(() => {
  console.log('timer1')
  Promise.resolve().then(() => {
    console.log('promise2')
  })
}, 0)
console.log('start');
```

```js
start
promise1
timer1
promise2
timer2
```

代码执行过程如下：

1.  首先，`Promise.resolve().then`是一个微任务，加入微任务队列
2.  执行timer1，它是一个宏任务，加入宏任务队列
3.  继续执行下面的同步代码，打印出`start`
4.  这样第一轮宏任务就执行完了，开始执行微任务`Promise.resolve().then`，打印出`promise1`
5.  遇到`timer2`，它是一个宏任务，将其加入宏任务队列，此时宏任务队列有两个任务，分别是`timer1`、`timer2`；
6.  这样第一轮微任务就执行完了，开始执行第二轮宏任务，首先执行定时器`timer1`，打印`timer1`；
7.  遇到`Promise.resolve().then`，它是一个微任务，加入微任务队列
8.  开始执行微任务队列中的任务，打印`promise2`；
9.  最后执行宏任务`timer2`定时器，打印出`timer2`；

#### 状态改变

```js
const promise = new Promise((resolve, reject) => {
    resolve('success1');
    reject('error');
    resolve('success2');
});
promise.then((res) => {
    console.log('then:', res);
}).catch((err) => {
    console.log('catch:', err);
})
```

```js
then：success1
```

**Promise的状态在发生变化之后，就不会再发生变化**。开始状态由`pending`变为`resolve`，说明已经变为已完成状态，下面的两个状态的就不会再执行，同时下面的catch也不会捕获到错误。

```js
const promise1 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve('success')
  }, 1000)
})
const promise2 = promise1.then(() => {
  throw new Error('error!!!')
})
console.log('promise1', promise1)
console.log('promise2', promise2)
setTimeout(() => {
  console.log('promise1', promise1)
  console.log('promise2', promise2)
}, 2000)
```

```js
promise1 Promise {<pending>}
promise2 Promise {<pending>}

Uncaught (in promise) Error: error!!!
promise1 Promise {<fulfilled>: "success"}
promise2 Promise {<rejected>: Error: error!!}
```

只有执行了resolve()或者reject()状态才会发生改变   



```js
Promise.reject('err!!!')
  .then((res) => {
    console.log('success', res)
  }, (err) => {
    console.log('error', err)
  }).catch(err => {
    console.log('catch', err)
  })
```

```js
error err!!!
```

`.then`函数中的两个参数：

-   第一个参数是用来处理Promise成功的函数
-   第二个则是处理失败的函数

也就是说`Promise.resolve('1')`的值会进入成功的函数，`Promise.reject('2')`的值会进入失败的函数。

在这道题中，错误直接被`then`的第二个参数捕获了，所以就不会被`catch`捕获了，输出结果为：`error err!!!'`



#### 链式调用传值

```js
Promise.resolve(1)
  .then(res => {
    console.log(res);
    return 2;
  })
  .catch(err => {
    return 3;
  })
  .then(res => {
    console.log(res);
  });
```

```
1   
2
```

Promise是可以链式调用的，由于每次调用 `.then` 或者 `.catch` 都会返回一个新的 promise，从而实现了链式调用, 它并不像一般任务的链式调用一样return this。

上面的输出结果之所以依次打印出1和2，是因为`resolve(1)`之后走的是第一个then方法，并没有进catch里，所以第二个then中的res得到的实际上是第一个then的返回值。并且return 2会被包装成`resolve(2)`，被最后的then打印输出2



```js
Promise.resolve(1)
  .then(res => {
    console.log(res);
    throw err
  })
  .catch(err => {
    return 3;
  })
  .then(res => {
    console.log(res);
  });
```

```
1
3
```

上面的输出结果之所以依次打印出1和3，是因为`resolve(1)`之后走的是第一个then方法，抛出错误进catch里，所以第二个then中的res得到的实际上是第catch的返回值。并且return 3会被包装成`reject(3)`，被最后的then打印输出3



```js
Promise.resolve(1)
  .then(2)
  .then(Promise.resolve(3))
  .then(console.log)
```

```js
1
Promise {<fulfilled>: undefined}
```

Promise.resolve方法的参数如果是一个原始值，或者是一个不具有then方法的对象，则Promise.resolve方法返回一个新的Promise对象，状态为resolved，Promise.resolve方法的参数，会同时传给回调函数

**then方法接受的参数是函数**，而如果传递的并非是一个函数，它实际上会将其解释为then(null)，这就会导致**前一个Promise的结果会传递下面**

好多的then，实际上只需要记住一个原则：`.then` 或`.catch` 的参数期望是函数，传入非函数则会发生**值透传**

**第一个then和第二个then中传入的都不是函数，一个是数字，一个是对象，因此发生了透传，将`resolve(1)` 的值直接传到最后一个then里，直接打印出1**

```js
Promise.resolve().then(() => {
  return new Error('error!!!')
}).then(res => {
  console.log("then: ", res)
}).catch(err => {
  console.log("catch: ", err)
})
```

```js
"then: " "Error: error!!!"
```

返回任意一个非 promise 的值都会被包裹成 promise 对象，因此这里的`return new Error('error!!!')`也被包裹成了`return Promise.resolve(new Error('error!!!'))`，因此它会被then捕获而不是catch。



```js
const promise = Promise.resolve().then(() => {
  return promise;
})
promise.catch(console.err)

```

```
Uncaught (in promise) TypeError: Chaining cycle detected for promise #<Promise>

```

`.then` 或 `.catch` 返回的值不能是 promise 本身，否则会造成死循环。





#### finally



```js
Promise.resolve('1')
  .then(res => {
    console.log(res)
  })
  .finally(() => {
    console.log('finally')
  })
Promise.resolve('2')
  .finally(() => {
    console.log('finally2')
  	return '我是finally2返回的值'
  })
  .then(res => {
    console.log('finally2后面的then函数', res)
  })
```

```js
1
finally2
finally
finally2后面的then函数 2
```

`.finally()`一般用的很少，只要记住以下几点就可以了：

-   `.finally()`方法不管Promise对象最后的状态如何都会执行
-   `.finally()`方法的回调函数不接受任何的参数，也就是说你在`.finally()`函数中是无法知道Promise最终的状态是`resolved`还是`rejected`的
-   它最终返回的默认会是一个上一次的Promise对象值，不过如果抛出的是一个异常则返回异常的Promise对象。
-   finally本质上是then方法的特例

```js
Promise.resolve('1')
  .finally(() => {
    console.log('finally1')
    throw new Error('我是finally中抛出的异常')
  })
  .then(res => {
    console.log('finally后面的then函数', res)
  })
  .catch(err => {
    console.log('捕获错误', err)
  })
```

```js
'finally1'  
'捕获错误'    Error: 我是finally中抛出的异常
```









```js
var p = new Promise(resolve => {
	console.log(4);
	resolve(5);
});
function func1() {
	console.log(1);
	function func2() {
		setTimeout(() => {
			console.log(2);
		});
	}
	func2();
}
func1();
console.log(3);
p.then(resolved => {
	console.log(resolved)
}
).then(() => {
	console.log(6)
});
```



### this指向

#### 1.

```js
function foo() {
  console.log( this.a );
}

function doFoo() {
  foo();
}

var obj = {
  a: 1,
  doFoo: doFoo
};

var a = 2; 
obj.doFoo()

//2
```

在Javascript中，this指向函数执行时的当前对象。**在执行foo的时候，执行环境就是doFoo函数，执行环境为全局**。所以，foo中的this是指向window的，所以会打印出2。

#### 2.

```js
var a = 10
var obj = {
  a: 20,
  say: () => {
    console.log(this.a)
  }
}
obj.say() 

var anotherObj = { a: 30 } 
obj.say.apply(anotherObj) 
// 10  10
```

我么知道，箭头函数时不绑定this的，它的this来自原其父级所处的上下文，所以首先会打印全局中的 a 的值10。后面虽然让say方法指向了另外一个对象，但是仍不能改变箭头函数的特性，它的this仍然是指向全局的，所以依旧会输出10。

如果是普通函数，那么就会有完全不一样的结果：

```js
var a = 10  
var obj = {  
  a: 20,  
  say(){
    console.log(this.a)  
  }  
}  
obj.say()   
var anotherObj={a:30}   
obj.say.apply(anotherObj)
//20 30
```

say方法中的this就会指向他所在的对象，输出其中的a的值

#### 3.

```js
function a() {
  console.log(this);
}
a.call(null);
//Window{}
```

如果第一个参数传入的对象调用者是null或者undefined，call方法将把全局对象（浏览器上是window对象）作为this的值。所以，不管传入null 还是 undefined，其this都是全局对象window。所以，在浏览器上答案是输出 window 对象。

要注意的是，在严格模式中，null 就是 null，undefined 就是 undefined

```js
'use strict';

function a() {
    console.log(this);
}
a.call(null); // null
a.call(undefined); // undefined
```

#### 4.

```js
var obj = { 
  name : 'cuggz', 
  fun : function(){ 
    console.log(this.name); 
  } 
} 
obj.fun()     // cuggz
new obj.fun() // undefined
```

使用new构造函数时，其this指向的是全局环境window。



#### 5.

```js

var obj = {
   say: function() {
     var f1 = () =>  {
       console.log("1111", this);
     }
     f1();
   },
   pro: {
     getPro:() =>  {
        console.log(this);
     }
   }
}
var fn = obj.say;
fn();
obj.say();
obj.pro.getPro();

//1111 window{}
//1111 obj{}
//window{}
```

1.  fn()，fn是在全局执行的，而f1是箭头函数，它是没有绑定this的，它的this指向其父级的this，其父级say方法的this指向的是全局作用域，所以会打印出window；
2.  obj.say()，谁调用say，say 的this就指向谁，所以此时this指向的是obj对象；
3.  obj.pro.getPro()，我们知道，箭头函数时不绑定this的，getPro处于pro中，而对象不构成单独的作用域，所以箭头的函数的this就指向了全局作用域window。

#### 6.

```js
var myObject = {
    foo: "bar",
    func: function() {
        var self = this;
        console.log(this.foo);  
        console.log(self.foo);  
        (function() {
            console.log(this.foo);  
            console.log(self.foo);  
        }());
    }
};
myObject.func();
//bar bar undefined bar
```

1.  首先func是由myObject调用的，this指向myObject。又因为var self = this;所以self指向myObject。
2.  这个立即执行匿名函数表达式是由window调用的，this指向window 。立即执行匿名函数的作用域处于myObject.func的作用域中，在这个作用域找不到self变量，沿着作用域链向上查找self变量，找到了指向 myObject对象的self。

#### 7.

```js
window.number = 2;
var obj = {
 number: 3,
 db1: (function(){
   console.log(this);
   this.number *= 4;
   return function(){
     console.log(this);
     this.number *= 5;
   }
 })()
}
var db1 = obj.db1;
db1();
obj.db1();
console.log(obj.number);     // 15
console.log(window.number);  // 40
```

1.  执行db1()时，this指向全局作用域，所以window.number * 4 = 8，然后执行匿名函数， 所以window.number * 5 = 40；
2.  执行obj.db1();时，this指向obj对象，执行匿名函数，所以obj.numer * 5 = 15。

#### 8.

```javascript
var length = 10;
function fn() {
    console.log(this.length);
}
 
var obj = {
  length: 5,
  method: function(fn) {
    fn();
    arguments[0]();
  }
};
 
obj.method(fn, 1);
//10 2
```

1.  第一次执行fn()，this指向window对象，输出10。
2.  第二次执行arguments[0]，相当于arguments调用方法，this指向arguments，而这里传了两个参数，故输出arguments长度为2。

#### 9.

```js
var a = 1;
function printA(){
  console.log(this.a);
}
var obj={
  a:2,
  foo:printA,
  bar:function(){
    printA();
  }
}

obj.foo(); // 2
obj.bar(); // 1
var foo = obj.foo;
foo(); // 1
```

1.  obj.foo()，foo 的this指向obj对象，所以a会输出2；
2.  obj.bar()，printA在bar方法中执行，所以此时printA的this指向的是window，所以会输出1；
3.  foo()，foo是在全局对象中执行的，所以其this指向的是window，所以会输出1；

#### 10.

```js
var x = 3;
var y = 4;
var obj = {
    x: 1,
    y: 6,
    getX: function() {
        var x = 5;
        return function() {
            return this.x;
        }();
    },
    getY: function() {
        var y = 7;
        return this.y;
    }
}
console.log(obj.getX()) // 3
console.log(obj.getY()) // 6
```

1.  我们知道，匿名函数的this是指向全局对象的，所以this指向window，会打印出3；
2.  getY是由obj调用的，所以其this指向的是obj对象，会打印出6。

#### 11.

```js
 var a = 10; 
 var obt = { 
   a: 20, 
   fn: function(){ 
     var a = 30; 
     console.log(this.a)
   } 
 }
 obt.fn();  // 20
 obt.fn.call(); // 10
 (obt.fn)(); // 20
```

1.   obt.fn()，fn是由obt调用的，所以其this指向obt对象，会打印出20；
2.   obt.fn.call()，这里call的参数啥都没写，就表示null，我们知道如果call的参数为undefined或null，那么this就会指向全局对象this，所以会打印出 10；
3.   (obt.fn)()， 这里给表达式加了括号，而括号的作用是改变表达式的运算顺序，而在这里加与不加括号并无影响；相当于  obt.fn()，所以会打印出 20；

#### 12.

```js
function a(xx){
  this.x = xx;
  return this
};
var x = a(5);
var y = a(6);

console.log(x.x)  // undefined
console.log(y.x)  // 6

```

1.  最关键的就是var x = a(5)，函数a是在全局作用域调用，所以函数内部的this指向window对象。**所以 this.x = 5 就相当于：window.x = 5。**之后 return this，也就是说 var x = a(5) 中的x变量的值是window，这里的x将函数内部的x的值覆盖了。然后执行console.log(x.x)， 也就是console.log(window.x)，而window对象中没有x属性，所以会输出undefined。
2.  当指向y.x时，会给全局变量中的x赋值为6，所以会打印出6。

#### 13.

```js
function foo(something){
    this.a = something
}

var obj1 = {
    foo: foo
}

var obj2 = {}

obj1.foo(2); 
console.log(obj1.a); // 2

obj1.foo.call(obj2, 3);
console.log(obj2.a); // 3

var bar = new obj1.foo(4)
console.log(obj1.a); // 2
console.log(bar.a); // 4

```

1.  首先执行obj1.foo(2); 会在obj中添加a属性，其值为2。之后执行obj1.a，a是右obj1调用的，所以this指向obj，打印出2；
2.  执行 obj1.foo.call(obj2, 3) 时，会将foo的this指向obj2，后面就和上面一样了，所以会打印出3；
3.  obj1.a会打印出2；
4.  最后就是考察this绑定的优先级了，new 绑定是比隐式绑定优先级高，所以会输出4。

#### 14.

```js
function foo(something){
    this.a = something
}

var obj1 = {}

var bar = foo.bind(obj1);
bar(2);
console.log(obj1.a); // 2

var baz = new bar(3);
console.log(obj1.a); // 2
console.log(baz.a); // 3
```

主要都是考察this绑定的优先级。记住以下结论即可：**this绑定的优先级：new绑定 > 显式绑定 > 隐式绑定 > 默认绑定**

### 作用域变量提升



### 原型继承